### ISSUE TITLE
Ehi there

### ISSUE THREAD

**Issue by BigNerd95** [0ki/mikrotik-tools#1]
Hi! I just see your slides (http://kirils.org/slides/2017-10-21_MT_Hacktivity_pub.pdf)

I think you can be interested in these my two projects:
https://github.com/BigNerd95/RouterOS-Backup-Tools
https://github.com/BigNerd95/Chimay-Red

I then have a 0day to jailbreak RouterOS without using npk.
We can talk about this in PM.

**Comment by 0ki** [comment]
Oh, nice. I also recreated and improved on the 1day quite some time ago, but have not published it. Brave move on your part!
