### ISSUE TITLE
supout.txt

### ISSUE THREAD

**Issue by ramyc46** [0ki/mikrotik-tools#10]
Dear
I am a beginner
how I can use encode_supout.py and decode_supout.py
I have supout.txt and I cannot encode it
 I need Command Line to run it
regards

**Comment by Chupaka** [comment]
```./decode_supout.py supout.rif``` in Command Line

**Comment by ramyc46** [comment]
![1](https://user-images.githubusercontent.com/10817724/56843870-ae0a8000-68af-11e9-8dfa-cf26cebbf08b.PNG)
![2](https://user-images.githubusercontent.com/10817724/56843871-ae0a8000-68af-11e9-829a-72ffc44af084.PNG)
![3](https://user-images.githubusercontent.com/10817724/56843872-ae0a8000-68af-11e9-910b-cfff36dfc8f1.PNG)

**Comment by Chupaka** [comment]
Then `python decode_supout.py supout.rif` in Command Line. Not in Python interpreter.

**Comment by ramyc46** [comment]
What is the correct interpreter?

**Comment by Chupaka** [comment]
Python 2.7 is the correct interpreter.
