### ISSUE TITLE
Can't decode passwords

### ISSUE THREAD

**Issue by lorenzobucci** [0ki/mikrotik-tools#13]
My RouterOS version is 6.45.3 and I want to extract user data from my backup.
decode_backup script works normally but decode_user reports all data except passwords.
In addition, are shown two parameters (_r20 and _r21) with hexadecimal ascii characters.
Version 6.45.3 is probably not compatible?
Thanks for the support!

**Comment by ps-apalon** [comment]
Correct, in 6.45.1 they finally removed insecure passwords storage, since then there's no way to decode passwords quickly.

**Comment by Chupaka** [comment]
Correct, in 6.45.1 they finally removed insecure passwords storage, since then there's no way to decode passwords quickly.

**Comment by lorenzobucci** [comment]
So is there really no way to extract passwords?

**Comment by ps-apalon** [comment]
Correct

**Comment by Chupaka** [comment]
Correct

**Comment by 0ki** [comment]
Yes, that's a good thing.

But you could try to get the passwords by using a dictionary attack. The cryptographical parameters needed for that are stored in r20 and r21.

**Comment by lorenzobucci** [comment]
I understand, now i have an off topic question
Would there be any way to add a new user to the backup file?
For example: i download the current backup which contains two users, i add a third user to the backup file (without password or with a known password), finally i restore the modified backup. Is there any way to do it and would it work?

**Comment by 0ki** [comment]
Yes.
