### ISSUE TITLE
winbox packet decoder

### ISSUE THREAD

**Issue by yalpanian** [0ki/mikrotik-tools#5]
is there any tools to decode Winbox communication ?
simple request sent by Winbox :

`\x37\x01\x00\x35\x4d\x32\x05\x00\xff\x01\x06\x00\xff\x09\x01\x07\x00\xff\x09\x07\x01\x00\x00\x21\x04\x6c\x69\x73\x74\x02\x00\xff\x88\x02\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x01\x00\xff\x88\x02\x00\x02\x00\x00\x00\x02\x00\x00\x00`

**Comment by 0ki** [comment]
I am not aware of any tools. I've started looking into it some time ago, but haven't actually written anything useful. If you find any, please let us know.

**Comment by 0x2b3bfa0** [comment]
There seem to be some WinBox protocol implementations on GitHub. Maybe is possible to adapt them.

https://github.com/lblasc/python-rosapi
https://github.com/vshn/tikapy

**Edit:** I answered mindlessly, sorry. These implementations are for the API.

**Comment by Chupaka** [comment]
@crushedice2000 these are not WinBox protocol, it's RouterOS API. Completely different things.

**Comment by 0x2b3bfa0** [comment]
@Chupaka: sorry, you're right!

**Comment by yalpanian** [comment]
@0ki thank you . I've figure out that request is encrypted by Winbox. for my purpose i just disabled the encrypted communication and i found out what i need . you can check my little project's result in https://github.com/BasuCert/WinboxPoC

**Comment by bCake** [comment]
https://github.com/Cisco-Talos/Winbox_Protocol_Dissector

**Comment by 0ki** [comment]
Thank you! This is great!
